

CREATE DATABASE IF NOT EXISTS `YTTERBIUM HIGH`;
USE `YTTERBIUM HIGH`;



DROP TABLE IF EXISTS `DEPARTMENTS`;

CREATE TABLE `DEPARTMENTS` (
  `DEPARTMENT ID` VARCHAR(255) NOT NULL, 
  `DEPARTMENT NAME` VARCHAR(255) NOT NULL, 
  PRIMARY KEY (`DEPARTMENT NAME`)
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;

INSERT INTO `DEPARTMENTS` (`DEPARTMENT ID`, `DEPARTMENT NAME`) VALUES ('YD10', 'MATHEMATICS');
INSERT INTO `DEPARTMENTS` (`DEPARTMENT ID`, `DEPARTMENT NAME`) VALUES ('YD02', 'LANGUAGES');
INSERT INTO `DEPARTMENTS` (`DEPARTMENT ID`, `DEPARTMENT NAME`) VALUES ('YD03', 'SCIENCE');
INSERT INTO `DEPARTMENTS` (`DEPARTMENT ID`, `DEPARTMENT NAME`) VALUES ('YD43', 'HUMANITIES');
INSERT INTO `DEPARTMENTS` (`DEPARTMENT ID`, `DEPARTMENT NAME`) VALUES ('YD12', 'TECHNICALS');
# 5 records



DROP TABLE IF EXISTS `DORMITORY TABLE`;

CREATE TABLE `DORMITORY TABLE` (
  `DORM NAME` VARCHAR(255) NOT NULL, 
  PRIMARY KEY (`DORM NAME`)
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;


INSERT INTO `DORMITORY TABLE` (`DORM NAME`) VALUES ('STANFORD');
INSERT INTO `DORMITORY TABLE` (`DORM NAME`) VALUES ('ST.LOUIS');
INSERT INTO `DORMITORY TABLE` (`DORM NAME`) VALUES ('PORTLAND');
INSERT INTO `DORMITORY TABLE` (`DORM NAME`) VALUES ('AUSTIN');
INSERT INTO `DORMITORY TABLE` (`DORM NAME`) VALUES ('TEXAS');
INSERT INTO `DORMITORY TABLE` (`DORM NAME`) VALUES ('MICHIGAN');
INSERT INTO `DORMITORY TABLE` (`DORM NAME`) VALUES ('WASHINGTON');
INSERT INTO `DORMITORY TABLE` (`DORM NAME`) VALUES ('DENVER');
INSERT INTO `DORMITORY TABLE` (`DORM NAME`) VALUES ('ATLAS');
INSERT INTO `DORMITORY TABLE` (`DORM NAME`) VALUES ('YORK');
# 10 records



DROP TABLE IF EXISTS `FEES PAYMENT`;

CREATE TABLE `FEES PAYMENT` (
  `STUDENT ID` INTEGER NOT NULL DEFAULT 0, 
  `STUDENT'S NAME` VARCHAR(255), 
  `FORM` VARCHAR(255), 
  `DATE OF PAYMENT` VARCHAR(255), 
  `AMOUNT PAID` INTEGER DEFAULT 0, 
  INDEX (`AMOUNT PAID`), 
  PRIMARY KEY (`STUDENT ID`)
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;



INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1101, 'YURI BELECOFF', 'FORM 3', '12/01/2018', 89000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1102, 'SAMUEL BROWLE', 'FORM 4', '12/01/2018', 55000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1103, 'FIDEL CASTRO', 'FORM 2', '13/01/2018', 45098);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1104, 'CHARLES PRESTON', 'FORM 1', '09/01/2018', 56777);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1105, 'ALFRED PENNYWORTH', 'FORM 4', '15/01/2018', 34000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1106, 'WAYNE BRUCE', 'FORM 3', '13/01/2018', 80300);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1107, 'CLARK KENT', 'FORM 2', '12/01/2018', 58000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1108, 'RAKE TYLER', 'FORM 1', '09/01/2018', 45000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1109, 'ALLEN BATHOLOMEW', 'FORM 1', '09/01/2018', 34000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1110, 'IRIS WEST', 'FORM 2', '09/01/2018', 32000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1111, 'JOHNNY CAGE', 'FORM 3', '15/01/2018', 32555);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1112, 'SONYA BLADE', 'FORM 4', '13/01/2018', 56000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1113, 'DIANA PRINCE', 'FORM 2', '09/01/2018', 59080);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1114, 'FAYORA AL', 'FORM 3', '15/01/2018', 56450);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1115, 'MITCHELLE CALL', 'FORM 4', '16/01/2018', 46444);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1116, 'PETER CULLEN', 'FORM 4', '15/01/2018', 38000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1117, 'MEGAN FOX', 'FORM 1', '09/01/2018', 59000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1118, 'TEGAN NOX', 'FORM 2', '10/01/2018', 63000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1119, 'ANESH WILDER', 'FORM 3', '13/01/2018', 68000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1120, 'TESSA HOPKINS', 'FORM 1', '10/01/2018', 29000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1121, 'MICHAEL LARRY', 'FORM 2', '13/01/2018', 34000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1122, 'VERS ZANDER', 'FORM 3', '11/01/2018', 30900);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1123, 'MARCUS MILES', 'FORM 4', '14/01/2018', 69001);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1124, 'BARBARA GORDON', 'FORM 2', '12/01/2018', 34000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1125, 'KOVINSKY PETER', 'FORM 1', '10/01/2018', 43000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1126, 'MAXWELL STEEL', 'FORM 4', '13/01/2018', 68050);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1127, 'LINDA PARK', 'FORM 3', '12/01/2018', 34580);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1128, 'LARA COVEY', 'FORM 3', '11/01/2018', 58009);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1129, 'DIANA HALL', 'FORM 4', '16/01/2018', 54600);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1130, 'WILKEANS BELLAMY', 'FORM 2', '13/01/2018', 37000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1131, 'YAMASHIRO TATSU', 'FORM 1', '10/01/2018', 23700);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1132, 'JAMES GORDON', 'FORM 1', '10/01/2018', 49080);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1133, 'JEANETTE SPEARS', 'FORM 2', '12/01/2018', 45000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1134, 'DICK GRAYSON', 'FORM 3', '12/01/2018', 57790);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1135, 'CIAN McCULLEN', 'FORM 4', '13/01/2018', 56900);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1136, 'NATASHA ROMANNOFF', 'FORM 4', '11/01/2018', 54000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1137, 'YELENA BELOVA', 'FORM 2', '11/01/2018', 69000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1138, 'HENDERSON DEAN', 'FORM 3', '13/01/2018', 100000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1139, 'JAMES WILLIAMS', 'FORM 1', '11/01/2018', 78000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1140, 'STEVE RODGERS', 'FORM 1', '11/01/2018', 56000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1141, 'TONY STARK', 'FORM 4', '13/01/2018', 34700);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1142, 'OLIVER QUEEN', 'FORM 2', '10/01/2018', 75300);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1143, 'DIGGLE JOHN', 'FORM 3', '13/01/2018', 33400);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1144, 'ALEGRA COLE', 'FORM 2', '09/01/2018', 67000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1145, 'ALEX HITCHNS', 'FORM 1', '12/01/2018', 77800);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1146, 'DINAH DRAKE', 'FORM 3', '14/01/2018', 67000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1147, 'HAL JORDAN', 'FORM 4', '12/01/2018', 65000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1148, 'DAMIEN WAYNE', 'FORM 3', '12/01/2018', 39800);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1149, 'JEREMY ETHIER', 'FORM 1', '12/01/2018', 67000);
INSERT INTO `FEES PAYMENT` (`STUDENT ID`, `STUDENT'S NAME`, `FORM`, `DATE OF PAYMENT`, `AMOUNT PAID`) VALUES (1150, 'FELICITY SMOKE', 'FORM 2', '13/01/2018', 51000);
# 50 records



DROP TABLE IF EXISTS `PARENTS TABLE`;

CREATE TABLE `PARENTS TABLE` (
  `ID NUMBER` INTEGER NOT NULL DEFAULT 0, 
  `NAME` VARCHAR(255), 
  `PHONE NUMBER` VARCHAR(255), 
  `E-MAIL` LONGTEXT, 
  INDEX (`PHONE NUMBER`), 
  PRIMARY KEY (`ID NUMBER`)
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;



INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (32008746, 'SARA  WACHOWSKI', '0724489352', 'wachowskihut@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (32884766, 'BRAUN HUNNER', '0746529346', 'hunnerbrraun@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (12880050, 'MARIA HALL', '0712357923', 'hallmaria@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (21775590, 'MARY WATSON', '0712354538', 'mjwatson@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (32880982, 'PARKER PENNYWORTH', '0724652399', 'butler800@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (12669390, 'THOMAS WAYNE', '0772395924', 'waynenterprises@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (11664056, 'JONATHAN KENT', '0725475474', 'kentjonathan@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (53221806, 'JULIA BIRCH', '0742566302', 'jewelbirch@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (56535789, 'HENRY ALLEN', '0745589772', 'theflash0999@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (12706756, 'JOE WEST', '0723635490', 'joecaptain@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (23457647, 'CASEY CAGE', '0724448253', 'hollywood400@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (12435987, 'JAX BRIGGS', '0759922435', 'pumpedup@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (75645078, 'ZEUS DRANGE', '0782114366', 'loordzeus344@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (25658368, 'ANORITE ZOD', '0745329347', 'anot67doz@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (25560061, 'MIKE MENTXER', '0726534899', 'mikementzer590@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (13660807, 'JOASH CULLEN', '0723549988', 'optimusprime@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (14577842, 'PETER GRIFFIN', '0799885531', 'petergriffin@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (55163875, 'TINA LINDE', '0701335765', 'lindetina@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (46454678, 'NAZIHA KHAN', '0484582465', 'khanziha@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (42676436, 'GIA HOPKINS', '0745218894', 'hopgia200@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (34685633, 'GARY OLSEN', '0712345890', 'garyolsen@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (54236673, 'SCOTT ANDERSON', '0114386390', 'anderscott@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (58767387, 'TIM MOORE', '0115309686', 'timoore340@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (62657653, 'JIM GORDON', '0745869400', 'jimgordon@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (12222358, 'ROWLAND SCOTT', '0792168400', 'scottrow@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (17905336, 'HANNAH STEEL', '0112890084', 'hannah56steel@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (45454267, 'JOANNE PARK', '0116799301', 'parkjoan@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (17798745, 'TOM GREEK', '0700112275', 'greektom900@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (10533457, 'LEWIS FORD', '0767723493', 'fordlewis@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (18956385, 'NICK FURY', '0160764967', 'nickfury@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (36577533, 'URAGIRI HANZO', '0723597283', 'hanzofire001@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (45674327, 'HANNIBAL GORDON', '0114862396', 'hangordon@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (42021176, 'DAVE SEVILLE', '0712435457', 'daveseville@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (96637434, 'HILDAH GRAYSON', '0735283652', 'hilgrayso004@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (57456768, 'DRIOSE McCULLEN', '0749812355', 'eldergodz908@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (34558807, 'MELINA KYNYASEV', '0745993468', 'melkyas@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (43598765, 'ALEXEI KYNYASEV', '0711045824', 'alexeired34@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (12378659, 'FRANK PIKE', '0747739624', 'pikfrank@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (35468978, 'GARY BIRT', '0118454858', 'garybirt@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (89765994, 'KATHERINE SUMMERS', '0783527573', 'katsummer@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (23459744, 'HOWARD STARK', '0735475862', 'starkhow100@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (56455696, 'ROBERT QUEEN', '0117590046', 'queenrob67@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (24398769, 'JOHN STEWART', '0734454555', 'stewartjohn@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (23456897, 'ROBERT COLE', '0117590352', 'robcole@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (23458765, 'TIM COLE', '0715764278', 'cole3324@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (23456876, 'MARTHA DRAKE', '0112270565', 'drakemartha@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (47931144, 'TIMOTHY JORDAN', '0753768578', 'jordantimothy@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (14687457, 'TALIA GHUL', '0788442211', 'taliaghul@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (69900002, 'YALE ETHIER', '0712345678', 'yaleethier@gmail.com');
INSERT INTO `PARENTS TABLE` (`ID NUMBER`, `NAME`, `PHONE NUMBER`, `E-MAIL`) VALUES (45352444, 'CHARITY HETHER', '0787654321', 'charityhether@gmail.com');
# 50 records


DROP TABLE IF EXISTS `REGISTRATION TABLE`;

CREATE TABLE `REGISTRATION TABLE` (
  `STUDENT ID` INTEGER NOT NULL DEFAULT 0, 
  `DATE OF REGISTRATION` DATETIME, 
  `STUDENT'S NAME` VARCHAR(255), 
  `PARENT'S NAME` VARCHAR(255), 
  PRIMARY KEY (`STUDENT ID`)
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;


INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1101, '2016-01-12 00:00:00', 'YURI BELECOFF', 'SARA  WACHOWSKI');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1102, '2015-01-12 00:00:00', 'SAMUEL BROWLE', 'BRAUN HUNNER');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1103, '2017-01-13 00:00:00', 'FIDEL CASTRO', 'MARIA HALL');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1104, '2018-01-09 00:00:00', 'CHARLES PRESTON', 'MARY WATSON');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1105, '2015-01-15 00:00:00', 'ALFRED PENNYWORTH', 'PARKER PENNYWORTH');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1106, '2016-01-13 00:00:00', 'WAYNE BRUCE', 'THOMAS WAYNE');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1107, '2017-01-12 00:00:00', 'CLARK KENT', 'JONATHAN KENT');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1108, '2018-01-09 00:00:00', 'RAKE TYLER', 'JULIA BIRCH');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1109, '2018-01-09 00:00:00', 'ALLEN BATHOLOMEW', 'HENRY ALLEN');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1110, '2017-01-09 00:00:00', 'IRIS WEST', 'JOE WEST');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1111, '2016-01-15 00:00:00', 'JOHNNY CAGE', 'CASEY CAGE');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1112, '2015-01-13 00:00:00', 'SONYA BLADE', 'JAX BRIGGS');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1113, '2018-01-09 00:00:00', 'DIANA PRINCE', 'ZEUS DRANGE');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1114, '2016-01-15 00:00:00', 'FAYORA AL', 'ANORITE ZOD');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1115, '2015-01-16 00:00:00', 'MITCHELLE CALL', 'MIKE MENTXER');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1116, '2015-01-15 00:00:00', 'PETER CULLEN', 'JOASH CULLEN');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1117, '2018-01-09 00:00:00', 'MEGAN FOX', 'PETER GRIFFIN');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1118, '2017-01-10 00:00:00', 'TEGAN NOX', 'TINA LINDE');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1119, '2016-01-13 00:00:00', 'ANESH WILDER', 'NAZIHA KHAN');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1120, '2018-01-10 00:00:00', 'TESSA HOPKINS', 'GIA HOPKINS');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1121, '2017-01-13 00:00:00', 'MICHAEL LARRY', 'GARY OLSEN');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1122, '2016-01-11 00:00:00', 'VERS ZANDER', 'SCOTT ANDERSON');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1123, '2015-01-14 00:00:00', 'MARCUS MILES', 'TIM MOORE');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1124, '2017-01-12 00:00:00', 'BARBARA GORDON', 'JIM GORDON');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1125, '2018-01-10 00:00:00', 'KOVINSKY PETER', 'ROWLAND SCOTT');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1126, '2015-01-13 00:00:00', 'MAXWELL STEEL', 'HANNAH STEEL');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1127, '2016-01-12 00:00:00', 'LINDA PARK', 'JOANNE PARK');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1128, '2016-01-11 00:00:00', 'LARA COVEY', 'TOM GREEK');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1129, '2015-01-16 00:00:00', 'DIANA HALL', 'LEWIS FORD');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1130, '2017-01-13 00:00:00', 'WILKEANS BELLAMY', 'NICK FURY');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1131, '2018-01-10 00:00:00', 'YAMASHIRO TATSU', 'URAGIRI HANZO');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1132, '2018-01-10 00:00:00', 'JAMES GORDON', 'HANNIBAL GORDON');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1133, '2017-01-12 00:00:00', 'JEANETTE SPEARS', 'DAVE SEVILLE');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1134, '2016-01-12 00:00:00', 'DICK GRAYSON', 'HILDAH GRAYSON');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1135, '2015-01-13 00:00:00', 'CIAN McCULLEN', 'DRIOSE McCULLEN');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1136, '2018-01-11 00:00:00', 'NATASHA ROMANNOFF', 'MELINA KYNYASEV');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1137, '2017-01-11 00:00:00', 'YELENA BELOVA', 'ALEXEI KYNYASEV');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1138, '2016-01-13 00:00:00', 'HENDERSON DEAN', 'FRANK PIKE');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1139, '2018-01-11 00:00:00', 'JAMES WILLIAMS', 'GARY BIRT');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1140, '2018-01-11 00:00:00', 'STEVE RODGERS', 'KATHERINE SUMMERS');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1141, '2015-01-13 00:00:00', 'TONY STARK', 'HOWARD STARK');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1142, '2017-01-10 00:00:00', 'OLIVER QUEEN', 'ROBERT QUEEN');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1143, '2016-01-13 00:00:00', 'DIGGLE JOHN', 'JOHN STEWART');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1144, '2017-01-09 00:00:00', 'ALEGRA COLE', 'ROBERT COLE');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1145, '2018-01-12 00:00:00', 'ALEX HITCHNS', 'TIM COLE');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1146, '2016-01-14 00:00:00', 'DINAH DRAKE', 'MARTHA DRAKE');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1147, '2015-01-12 00:00:00', 'HAL JORDAN', 'TIMOTHY JORDAN');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1148, '2016-01-12 00:00:00', 'DAMIEN WAYNE', 'TALIA GHUL');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1149, '2018-01-12 00:00:00', 'JEREMY ETHIER', 'YALE ETHIER');
INSERT INTO `REGISTRATION TABLE` (`STUDENT ID`, `DATE OF REGISTRATION`, `STUDENT'S NAME`, `PARENT'S NAME`) VALUES (1150, '2017-01-13 00:00:00', 'FELICITY SMOKE', 'CHARITY HETHER');
# 50 records



DROP TABLE IF EXISTS `STUDENTS' TABLE`;

CREATE TABLE `STUDENTS' TABLE` (
  `STUDENT ID` INTEGER NOT NULL DEFAULT 0, 
  `NAME` VARCHAR(255), 
  `GENDER` VARCHAR(255), 
  `DATE OF BIRTH` DATETIME, 
  `FORM` VARCHAR(255), 
  `DORMITORY` VARCHAR(255), 
  `PHONE NUMBER` VARCHAR(255), 
  `SUBJECTS TAKEN` LONGTEXT, 
  PRIMARY KEY (`STUDENT ID`), 
  INDEX (`PHONE NUMBER`)
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;



INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1101, 'YURI BELECOFF', 'MALE', '2001-06-23 00:00:00', 'FORM 3', 'AUSTIN', '0724489352', 'BIOLOGY;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;ENGLISH;FRENCH;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1102, 'SAMUEL BROWLE', 'MALE', '2000-08-24 00:00:00', 'FORM 4', 'DENVER', '0746529346', 'AGRICULTURE;BIOLOGY;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;ENGLISH;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1103, 'FIDEL CASTRO', 'MALE', '2002-04-16 00:00:00', 'FORM 2', 'ATLAS', '0712357923', 'BIOLOGY;CHEMISTRY;COMPUTER STUDIES;ENGLISH;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1104, 'CHARLES PRESTON', 'MALE', '2003-10-18 00:00:00', 'FORM 1', 'MICHIGAN', '0712354538', 'BIOLOGY;BUILDING CONSTRUCTION;CHEMISTRY;ENGLISH;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1106, 'WAYNE BRUCE', 'MALE', '2001-09-23 00:00:00', 'FORM 3', 'PORTLAND', '0772395924', 'BIOLOGY;CHEMISTRY;COMPUTER STUDIES;ENGLISH;HISTORY AND GOVERNMENT;MATHEMATICS;PHYSICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1105, 'ALFRED PENNYWORTH', 'MALE', '2000-08-23 00:00:00', 'FORM 4', 'ATLAS', '0724652399', 'BIOLOGY;CHEMISTRY;ENGLISH;FRENCH;GEOGRAPHY;MATHEMATICS;PHYSICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1107, 'CLARK KENT', 'MALE', '2002-03-04 00:00:00', 'FORM 2', 'AUSTIN', '0725475474', 'BIOLOGY;CHEMISTRY;ENGLISH;FRENCH;GEOGRAPHY;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1108, 'RAKE TYLER', 'MALE', '2003-12-04 00:00:00', 'FORM 1', 'AUSTIN', '0742566302', 'BIOLOGY;BUILDING CONSTRUCTION;CHEMISTRY;ENGLISH;GERMAN;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1109, 'ALLEN BATHOLOMEW', 'MALE', '2003-11-26 00:00:00', 'FORM 1', 'MICHIGAN', '0745589772', 'BIOLOGY;CHEMISTRY;COMPUTER STUDIES;ENGLISH;FRENCH;MATHEMATICS;PHYSICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1110, 'IRIS WEST', 'FEMALE', '2002-09-04 00:00:00', 'FORM 2', 'STANFORD', '0723635490', 'BIOLOGY;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;HISTORY AND GOVERNMENT;HOME SCIENCE;MATHEMATICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1111, 'JOHNNY CAGE', 'MALE', '2001-02-01 00:00:00', 'FORM 3', 'DENVER', '0724448253', 'BIOLOGY CHEMISTRY CHRISTIAN RELIGIOUS EDUCATION DRAWING AND DESIGN ENGLISH FRENCH HISTORY AND GOVERNMENT MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1112, 'SONYA BLADE', 'FEMALE', '2000-07-11 00:00:00', 'FORM 4', 'TEXAS', '0759922435', 'BIOLOGY;CHEMISTRY;ENGLISH;GEOGRAPHY;GERMAN;HOME SCIENCE;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1113, 'DIANA PRINCE', 'FEMALE', '2002-09-04 00:00:00', 'FORM 2', 'STANFORD', '0782114366', 'BIOLOGY;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;ENGLISH;FRENCH;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1114, 'FAYORA AL', 'FEMALE', '2001-02-01 00:00:00', 'FORM 3', 'ST.LOUIS', '0745329347', 'BIOLOGY;BUSINESS STUDIES;CHEMISTRY;ENGLISH;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1115, 'MITCHELLE CALL', 'FEMALE', '2001-01-25 00:00:00', 'FORM 4', 'ST.LOUIS', '0726534899', 'BIOLOGY;CHEMISTRY;DRAWING AND DESIGN;ENGLISH;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1116, 'PETER CULLEN', 'MALE', '2000-11-14 00:00:00', 'FORM 4', 'PORTLAND', '0723549988', 'BIOLOGY;BUSINESS STUDIES;CHEMISTRY;ENGLISH;GEOGRAPHY;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1117, 'MEGAN FOX', 'FEMALE', '2003-11-12 00:00:00', 'FORM 1', 'ST.LOUIS', '0799885531', 'BIOLOGY;BUSINESS STUDIES;CHEMISTRY;ENGLISH;HISTORY AND GOVERNMENT;ISLAMIC RELIGIOUS EDUCATION;KISWAHILI;MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1118, 'TEGAN NOX', 'FEMALE', '2002-09-04 00:00:00', 'FORM 2', 'STANFORD', '0701335765', 'BIOLOGY;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;ENGLISH;FRENCH;HOME SCIENCE;KISWAHILI;MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1119, 'ANESH WILDER', 'FEMALE', '2001-05-05 00:00:00', 'FORM 3', 'TEXAS', '0484582465', 'BIOLOGY;CHEMISTRY;ENGLISH;GERMAN;HISTORY AND GOVERNMENT;HOME SCIENCE;ISLAMIC RELIGIOUS EDUCATION;MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1120, 'TESSA HOPKINS', 'FEMALE', '2003-08-20 00:00:00', 'FORM 1', 'YORK', '0745218894', 'BIOLOGY;CHEMISTRY;ENGLISH;GEOGRAPHY;HOME SCIENCE;KISWAHILI;MATHEMATICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1121, 'MICHAEL LARRY', 'MALE', '2002-09-02 00:00:00', 'FORM 2', 'ATLAS', '0712345890', 'BIOLOGY;BUSINESS STUDIES;CHEMISTRY;ENGLISH;FRENCH;GEOGRAPHY;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1122, 'VERS ZANDER', 'FEMALE', '2001-06-07 00:00:00', 'FORM 3', 'WASHINGTON', '0114386390', 'BIOLOGY;CHEMISTRY;ENGLISH;HOME SCIENCE;ISLAMIC RELIGIOUS EDUCATION;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1123, 'MARCUS MILES', 'MALE', '2000-12-25 00:00:00', 'FORM 4', 'PORTLAND', '0115309686', 'BIOLOGY;CHEMISTRY;ENGLISH;GERMAN;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1124, 'BARBARA GORDON', 'FEMALE', '2002-04-01 00:00:00', 'FORM 2', 'YORK', '0745869400', 'BIOLOGY;CHEMISTRY;COMPUTER STUDIES;ENGLISH;GEOGRAPHY;MATHEMATICS;PHYSICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1125, 'KOVINSKY PETER', 'MALE', '2003-07-23 00:00:00', 'FORM 1', 'DENVER', '0792168400', 'BIOLOGY;CHEMISTRY;DRAWING AND DESIGN;ENGLISH;GEOGRAPHY;GERMAN;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1126, 'MAXWELL STEEL', 'MALE', '2000-11-02 00:00:00', 'FORM 4', 'PORTLAND', '0112890084', 'BIOLOGY;BUILDING CONSTRUCTION;CHEMISTRY;ENGLISH;GEOGRAPHY;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1127, 'LINDA PARK', 'FEMALE', '2001-06-23 00:00:00', 'FORM 3', 'STANFORD', '0116799301', 'BIOLOGY;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;DRAWING AND DESIGN;ENGLISH;HOME SCIENCE;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1128, 'LARA COVEY', 'FEMALE', '2001-01-22 00:00:00', 'FORM 3', 'WASHINGTON', '0700112275', 'BIOLOGY;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;DRAWING AND DESIGN;ENGLISH;HOME SCIENCE;ISLAMIC RELIGIOUS EDUCATION;MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1129, 'DIANA HALL', 'FEMALE', '2000-10-18 00:00:00', 'FORM 4', 'YORK', '0767723493', 'AGRICULTURE;BIOLOGY;CHEMISTRY;ENGLISH;GEOGRAPHY;KISWAHILI;MATHEMATICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1130, 'WILKEANS BELLAMY', 'MALE', '2002-07-06 00:00:00', 'FORM 2', 'MICHIGAN', '0160764967', 'BIOLOGY;CHEMISTRY;COMPUTER STUDIES;ENGLISH;GEOGRAPHY;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1131, 'YAMASHIRO TATSU', 'FEMALE', '2003-11-12 00:00:00', 'FORM 1', 'YORK', '0723597283', 'BIOLOGY;CHEMISTRY;ENGLISH;GERMAN;HISTORY AND GOVERNMENT;HOME SCIENCE;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1132, 'JAMES GORDON', 'MALE', '2003-06-18 00:00:00', 'FORM 1', 'MICHIGAN', '0114862396', 'BIOLOGY;BUSINESS STUDIES;CHEMISTRY;ENGLISH;GEOGRAPHY;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1133, 'JEANETTE SPEARS', 'FEMALE', '2002-09-29 00:00:00', 'FORM 2', 'WASHINGTON', '0712435457', 'AGRICULTURE;BIOLOGY;CHEMISTRY;ENGLISH;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1134, 'DICK GRAYSON', 'MALE', '2001-04-05 00:00:00', 'FORM 3', 'DENVER', '0735283652', 'BIOLOGY;BUSINESS STUDIES;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;ENGLISH;FRENCH;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1135, 'CIAN McCULLEN', 'MALE', '2000-01-15 00:00:00', 'FORM 4', 'AUSTIN', '0749812355', 'BIOLOGY;CHEMISTRY;COMPUTER STUDIES;ENGLISH;GEOGRAPHY;MATHEMATICS;PHYSICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1136, 'NATASHA ROMANNOFF', 'FEMALE', '2000-01-06 00:00:00', 'FORM 4', 'ST.LOUIS', '0745993468', 'BIOLOGY;BUSINESS STUDIES;CHEMISTRY;ENGLISH;HISTORY AND GOVERNMENT;HOME SCIENCE;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1137, 'YELENA BELOVA', 'FEMALE', '2002-02-17 00:00:00', 'FORM 2', 'STANFORD', '0711045824', 'BIOLOGY;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;DRAWING AND DESIGN;ENGLISH;HISTORY AND GOVERNMENT;KISWAHILI;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1138, 'HENDERSON DEAN', 'MALE', '2001-09-06 00:00:00', 'FORM 3', 'ATLAS', '0747739624', 'BIOLOGY;BUSINESS STUDIES;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;ENGLISH;GEOGRAPHY;KISWAHILI;MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1139, 'JAMES WILLIAMS', 'MALE', '2003-05-03 00:00:00', 'FORM 1', 'DENVER', '0118454858', 'BIOLOGY;BUILDING CONSTRUCTION;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;ENGLISH;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1140, 'STEVE RODGERS', 'MALE', '2003-01-26 00:00:00', 'FORM 1', 'MICHIGAN', '0783527573', 'BIOLOGY;BUILDING CONSTRUCTION;CHEMISTRY;ENGLISH;HISTORY AND GOVERNMENT;KISWAHILI;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1141, 'TONY STARK', 'MALE', '2000-01-22 00:00:00', 'FORM 4', 'PORTLAND', '0735475862', 'BIOLOGY;CHEMISTRY;COMPUTER STUDIES;ENGLISH;GEOGRAPHY;MATHEMATICS;PHYSICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1142, 'OLIVER QUEEN', 'MALE', '2002-09-07 00:00:00', 'FORM 2', 'PORTLAND', '0117590046', 'BIOLOGY;CHEMISTRY;COMPUTER STUDIES;ENGLISH;FRENCH;GEOGRAPHY;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1143, 'DIGGLE JOHN', 'MALE', '2001-05-18 00:00:00', 'FORM 3', 'DENVER', '0734454555', 'BIOLOGY;CHEMISTRY;ENGLISH;GEOGRAPHY;GERMAN;MATHEMATICS;PHYSICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1144, 'ALEGRA COLE', 'FEMALE', '2002-12-14 00:00:00', 'FORM 2', 'WASHINGTON', '0117590352', 'AGRICULTURE;BIOLOGY;BUSINESS STUDIES;CHEMISTRY;ENGLISH;GERMAN;HISTORY AND GOVERNMENT;MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1145, 'ALEX HITCHNS', 'MALE', '2003-01-04 00:00:00', 'FORM 1', 'ATLAS', '0715764278', 'BIOLOGY;BUSINESS STUDIES;CHEMISTRY;CHRISTIAN RELIGIOUS EDUCATION;ENGLISH;HISTORY AND GOVERNMENT;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1146, 'DINAH DRAKE', 'FEMALE', '2001-02-25 00:00:00', 'FORM 3', 'YORK', '0112270565', 'BIOLOGY;CHEMISTRY;ENGLISH;HISTORY AND GOVERNMENT;HOME SCIENCE;KISWAHILI;MATHEMATICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1147, 'MAHALIA JORDAN', 'FEMALE', '2000-01-20 00:00:00', 'FORM 4', 'YORK', '0753768578', 'BIOLOGY;CHEMISTRY;ENGLISH;GEOGRAPHY;GERMAN;HOME SCIENCE;KISWAHILI;MATHEMATICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1148, 'DAMIEN WAYNE', 'MALE', '2001-05-16 00:00:00', 'FORM 3', 'AUSTIN', '0788442211', 'BIOLOGY;CHEMISTRY;DRAWING AND DESIGN;ENGLISH;HISTORY AND GOVERNMENT;ISLAMIC RELIGIOUS EDUCATION;MATHEMATICS;PHYSICS');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1149, 'JEREMY ETHIER', 'MALE', '2003-01-16 00:00:00', 'FORM 1', 'MICHIGAN', '0712345678', 'BIOLOGY;BUSINESS STUDIES;ENGLISH;GERMAN;HISTORY AND GOVERNMENT;MATHEMATICS;PHYSICS;SPANISH');
INSERT INTO `STUDENTS' TABLE` (`STUDENT ID`, `NAME`, `GENDER`, `DATE OF BIRTH`, `FORM`, `DORMITORY`, `PHONE NUMBER`, `SUBJECTS TAKEN`) VALUES (1150, 'FELICITY SMOKE', 'FEMALE', '2002-01-13 00:00:00', 'FORM 2', 'TEXAS', '0787654321', 'BIOLOGY;CHEMISTRY;COMPUTER STUDIES;ENGLISH;HISTORY AND GOVERNMENT;MATHEMATICS;PHYSICS;SPANISH');
# 50 records



DROP TABLE IF EXISTS `SUBJECTS`;

CREATE TABLE `SUBJECTS` (
  `SUBJECT NAME` VARCHAR(255) NOT NULL, 
  `DEPARTMENT` VARCHAR(255), 
  PRIMARY KEY (`SUBJECT NAME`), 
  INDEX (`DEPARTMENT`)
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;



INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('MATHEMATICS', 'MATHEMATICS');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('ENGLISH', 'LANGUAGES');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('KISWAHILI', 'LANGUAGES');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('FRENCH', 'LANGUAGES');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('GERMAN', 'LANGUAGES');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('SPANISH', 'LANGUAGES');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('BIOLOGY', 'SCIENCE');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('CHEMISTRY', 'SCIENCE');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('PHYSICS', 'SCIENCE');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('GEOGRAPHY', 'HUMANITIES');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('HISTORY AND GOVERNMENT', 'HUMANITIES');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('CHRISTIAN RELIGIOUS EDUCATION', 'HUMANITIES');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('ISLAMIC RELIGIOUS EDUCATION', 'HUMANITIES');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('COMPUTER STUDIES', 'TECHNICALS');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('DRAWING AND DESIGN', 'TECHNICALS');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('BUILDING CONSTRUCTION', 'TECHNICALS');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('AGRICULTURE', 'TECHNICALS');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('BUSINESS STUDIES', 'TECHNICALS');
INSERT INTO `SUBJECTS` (`SUBJECT NAME`, `DEPARTMENT`) VALUES ('HOME SCIENCE', 'TECHNICALS');
# 19 records



DROP TABLE IF EXISTS `SUPPORT STAFF`;

CREATE TABLE `SUPPORT STAFF` (
  `ID NUMBER` INTEGER NOT NULL DEFAULT 0, 
  `EMPLOYEE ID` VARCHAR(255) NOT NULL, 
  `EMPLOYEE NAME` VARCHAR(255), 
  `GENDER` VARCHAR(255), 
  `OCCUPATION` VARCHAR(255), 
  INDEX (`EMPLOYEE ID`), 
  PRIMARY KEY (`EMPLOYEE ID`)
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;



INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (44330952, 'GD10', 'KEVIN KIBET', 'MALE', 'GUARD');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (46399012, 'GD01', 'JOEL KIPYEGON', 'MALE', 'GUARD');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (12335422, 'GD02', 'JOSHUA BUNDOTICH', 'MALE', 'GUARD');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (24365854, 'GD03', 'WILLIAM TUNAI', 'MALE', 'GUARD');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (66834256, 'GD04', 'BRIAN KIPRONO', 'MALE', 'GUARD');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (35751123, 'CLE01', 'STEVE NGAIWA', 'MALE', 'CLEANER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (67956346, 'CLE02', 'NYABARO SHEILA', 'FEMALE', 'CLEANER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (64597005, 'CLE03', 'NIGEL CLIFF', 'MALE', 'CLEANER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (35577943, 'CLE04', 'VINCENT NYANDEGE', 'MALE', 'CLEANER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (54343245, 'CLE05', 'RIRA CLIFF', 'MALE', 'CLEANER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (76543358, 'CLE06', 'CALEB BETT', 'MALE', 'CLEANER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (89765897, 'CLE07', 'ISAAC KIPCHUMBA', 'MALE', 'CLEANER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (23768311, 'CLE08', 'MEMUSI IAN', 'MALE', 'CLEANER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (87690000, 'CLE09', 'VICTOR  ZOLLA', 'MALE', 'CLEANER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (67554333, 'GR01', 'PHILLIP MATHEKA', 'MALE', 'GARDENER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (44255341, 'GR02', 'LUKA WERU', 'MALE', 'GARDENER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (13212234, 'GR03', 'OMONDI TIMON', 'MALE', 'GARDENER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (10978654, 'GR04', 'RICHARD VANCE', 'MALE', 'GARDENER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (11345765, 'GR05', 'DAIMLER BENZ', 'MALE', 'GARDENER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (65434511, 'LT02', 'PETER MUASYA', 'MALE', 'LAB TECHNICIAN');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (56486444, 'LT01', 'MEDIATRIX AKISA', 'FEMALE', 'LAB TECHNICIAN');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (24282468, 'LT04', 'ERIC MAITHYA', 'MALE', 'LAB TECHNICIAN');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (45324325, 'LT03', 'GRACE KILO', 'FEMALE', 'LAB TECHNICIAN');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (23456543, 'SCT1', 'ELIZABET WAMBUI', 'FEMALE', 'SECRETARY');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (75645439, 'SCT2', 'MARGARET CHEBET', 'FEMALE', 'SECRETARY');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (68754756, 'ACC2', 'AMOLLO REAGAN', 'MALE', 'ACCOUNTANT');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (68756635, 'ACC3', 'ASAVA MOSES', 'MALE', 'ACCOUNTANT');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (78565423, 'ACC9', 'IZALEEN MONIQUE', 'FEMALE', 'ACCOUNTANT');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (76579877, 'DRV1', 'GEORGE AMOTH', 'MALE', 'DRIVER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (90006754, 'DRV2', 'TIMOTHY YATOR', 'MALE', 'DRIVER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (76123455, 'DRV3', 'SAMUEL MEITEMEI', 'MALE', 'DRIVER');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (53653356, 'CK01', 'GEOFFREY MUREITHI', 'MALE', 'COOK');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (23456765, 'CK02', 'AKINYI NYMPHA', 'FEMALE', 'COOK');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (12345679, 'CK03', 'AKOTH LYDIAH', 'FEMALE', 'COOK');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (65425664, 'CK04', 'WAMBUI RISPER', 'FEMALE', 'COOK');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (76543456, 'CK05', 'JOY KAREN', 'FEMALE', 'COOK');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (89756764, 'LB06', 'WAYODI FAITH', 'FEMALE', 'LIBRARIAN');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (75646536, 'LB07', 'WAMUGI LINET', 'FEMALE', 'LIBRARIAN');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (87654356, 'NRS1', 'PRECIOUS HELLEN', 'FEMALE', 'NURSE');
INSERT INTO `SUPPORT STAFF` (`ID NUMBER`, `EMPLOYEE ID`, `EMPLOYEE NAME`, `GENDER`, `OCCUPATION`) VALUES (87656455, 'NRS2', 'SHIRLEEN ADEMBA', 'FEMALE', 'NURSE');
# 40 records



DROP TABLE IF EXISTS `TEACHERS' TABLE`;

CREATE TABLE `TEACHERS' TABLE` (
  `ID NUMBER` INTEGER NOT NULL DEFAULT 0, 
  `EMPLOYEE ID` VARCHAR(255) NOT NULL, 
  `FIRST NAME` VARCHAR(50), 
  `SURNAME` VARCHAR(255), 
  `GENDER` VARCHAR(255), 
  `DEPARTMENT` VARCHAR(255), 
  `SUBJECTS TAUGHT` LONGTEXT, 
  INDEX (`EMPLOYEE ID`), 
  PRIMARY KEY (`EMPLOYEE ID`), 
  INDEX (`DEPARTMENT`)
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;



INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (456637222, 'TR022', 'JANET', 'MISOI', 'FEMALE', 'HUMANITIES', 'HOME SCIENCE;KISWAHILI');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (459912843, 'TR111', 'BEATRICE', 'PRIOR', 'FEMALE', 'SCIENCE', 'AGRICULTURE;CHEMISTRY;HOME SCIENCE');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (243665565, 'TR138', 'OGAO', 'PATRICK', 'MALE', 'HUMANITIES', 'GEOGRAPHY;HISTORY AND GOVERNMENT');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (447728218, 'TR110', 'WASETH', 'ALLAN', 'MALE', 'TECHNICALS', 'BUILDING CONSTRUCTION;DRAWING AND DESIGN');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (128898465, 'TR700', 'CAITLIN', 'SNOW', 'FEMALE', 'SCIENCE', 'CHEMISTRY;PHYSICS');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (450932768, 'TR701', 'CISCO', 'RAMONE', 'MALE', 'LANGUAGES', 'KISWAHILI;SPANISH');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (265969575, 'TR040', 'MARGARET', 'GAINES', 'FEMALE', 'MATHEMATICS', 'MATHEMATICS;PHYSICS');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (236873000, 'TR431', 'EREN', 'YEAGER', 'MALE', 'LANGUAGES', 'ENGLISH;KISWAHILI');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (563937744, 'TR784', 'DANIEL', 'ESPOZITO', 'MALE', 'MATHEMATICS', 'GEOGRAPHY;MATHEMATICS');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (347222940, 'TR660', 'EBONY', 'MAGDALENE', 'FEMALE', 'HUMANITIES', 'GEOGRAPHY;ISLAMIC RELIGIOUS EDUCATION');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (904523380, 'TR391', 'JUNE', 'IMMACULATE', 'FEMALE', 'TECHNICALS', 'DRAWING AND DESIGN;HOME SCIENCE');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (983647313, 'TR826', 'CYNTHIA', 'MARAUD', 'FEMALE', 'LANGUAGES', 'GERMAN;ISLAMIC RELIGIOUS EDUCATION');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (334635375, 'TR055', 'ERWIN', 'TROLL', 'MALE', 'TECHNICALS', 'HOME SCIENCE;SPANISH');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (457722090, 'TR091', 'LEWIS', 'TEVIN', 'MALE', 'TECHNICALS', 'AGRICULTURE;BIOLOGY');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (116784990, 'TR001', 'ABRAHAM', 'DURKE', 'MALE', 'MATHEMATICS', 'CHRISTIAN RELIGIOUS EDUCATION;HISTORY AND GOVERNMENT');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (126649020, 'TR670', 'DREASON', 'RYAN', 'MALE', 'LANGUAGES', 'FRENCH;KISWAHILI');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (639920340, 'TR020', 'MIKASA', 'ACKERMAN', 'FEMALE', 'SCIENCE', 'CHEMISTRY;PHYSICS');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (114523650, 'TR450', 'SANAIPEI', 'RHODA', 'FEMALE', 'SCIENCE', 'BIOLOGY;CHEMISTRY');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (190363820, 'TR005', 'RICK', 'CASTLE', 'MALE', 'HUMANITIES', 'DRAWING AND DESIGN;ISLAMIC RELIGIOUS EDUCATION');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (133354090, 'TR008', 'DANIEL', 'DANCUN', 'MALE', 'MATHEMATICS', 'BUSINESS STUDIES;MATHEMATICS');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (169832560, 'TR004', 'JOASH', 'ALOO', 'MALE', 'LANGUAGES', 'CHEMISTRY;ENGLISH');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (216734000, 'TR007', 'QUENTIN', 'LANCE', 'MALE', 'HUMANITIES', 'BUSINESS STUDIES;GEOGRAPHY');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (236543210, 'TR010', 'SHARON', 'MARGARET', 'FEMALE', 'HUMANITIES', 'CHRISTIAN RELIGIOUS EDUCATION;HISTORY AND GOVERNMENT');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (214532330, 'TR006', 'JOAN', 'JETT', 'FEMALE', 'SCIENCE', 'CHEMISTRY;PHYSICS');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (236678160, 'TR011', 'TULLIP', 'PHINEHAS', 'FEMALE', 'LANGUAGES', 'ENGLISH;GERMAN');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (758884630, 'TR021', 'ZAINAB', 'HASSAN', 'FEMALE', 'HUMANITIES', 'GEOGRAPHY;ISLAMIC RELIGIOUS EDUCATION');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (256748880, 'TR012', 'MAURICE', 'TYMES', 'FEMALE', 'TECHNICALS', 'BUILDING CONSTRUCTION;DRAWING AND DESIGN');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (366746480, 'TR099', 'LEVI', 'ACKERMAN', 'MALE', 'MATHEMATICS', 'GERMAN;MATHEMATICS');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (126857940, 'TR002', 'ERIC', 'LANDO', 'MALE', 'SCIENCE', 'CHEMISTRY;PHYSICS');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (235688930, 'TR109', 'DANIEL', 'AKELLO', 'MALE', 'TECHNICALS', 'COMPUTER STUDIES;GERMAN');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (135689040, 'TR003', 'RICK', 'ASTLY', 'MALE', 'LANGUAGES', 'GERMAN;SPANISH');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (122435540, 'TR546', 'HANGE', 'DOWELL', 'FEMALE', 'LANGUAGES', 'ENGLISH;KISWAHILI');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (344858570, 'TR090', 'ERIC', 'SAVIN', 'MALE', 'MATHEMATICS', 'BUSINESS STUDIES;MATHEMATICS');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (536473224, 'TR023', 'KATE', 'BECKETT', 'FEMALE', 'SCIENCE', 'BIOLOGY;CHEMISTRY');
INSERT INTO `TEACHERS' TABLE` (`ID NUMBER`, `EMPLOYEE ID`, `FIRST NAME`, `SURNAME`, `GENDER`, `DEPARTMENT`, `SUBJECTS TAUGHT`) VALUES (123458801, 'TR009', 'WYCLIFFE', 'JUMA', 'MALE', 'MATHEMATICS', 'MATHEMATICS;PHYSICS');
# 35 records

